
networks:
  trafico-network:
    driver: bridge

volumes:
  db-data:
  redis-data:


services:
  mongo:
    image: mongo:6
    container_name: waze-db
    ports:
      - "27017:27017"  # Exponer el puerto estándar de MongoDB
    volumes:
      - db-data:/data/db #Izquierda del : es lo que esta en local, y lo que esta a la derecha es lo que se monta en el docker
    networks:
      - trafico-network
    restart: unless-stopped

  # Servicio de scraping de Waze
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: waze-scraper
    volumes:
      - ./scraper/src:/app/src
      - ./storage:/storage

    networks:
      - trafico-network
    restart: unless-stopped
    env_file:
      - mongo.env
    depends_on:
      - mongo
      - redis

  # Servicio de cache con Redis
  redis:
    image: redis:7-alpine
    container_name: waze-cache
    
    ports:
      - "6379:6379"    # Puerto estándar (para tus servicios)
        # Establece el límite de memoria (ej: 1GB)
    volumes:
      #- ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: ["redis-server", "--maxmemory 10mb", "--maxmemory-policy allkeys-lru"]
    # redis-server /usr/local/etc/redis/redis.conf
    networks:
      - trafico-network
    restart: unless-stopped
  # Servicio que administra el cache y políticas

  cache-service:
    build:
      context: ./cache-service
    container_name: waze-cache-service
    env_file: redis.env  # Esto debe estar dentro del servicio, no en la raíz
    networks:
      - trafico-network
    restart: unless-stopped


  traffic-generator:
    build:
      context: ./traffic-generator
      dockerfile: Dockerfile
    container_name: waze-traffic-gen
    volumes:
      - ./traffic-generator/src:/traffic-generator
      - ./storage:/storage
      - ./cache-service:/cache-service
    networks:
      - trafico-network
    env_file:
      - mongo.env # Si no se ponen estos env, no pesca, aunque no este en el 
      - redis.env
    depends_on:
      - mongo 
      - redis
    restart: no
  
  storage:
    build:
      context: ./storage
    container_name: waze-storage
    volumes:
      - ./storage:/storage
    env_file:
      - mongo.env
    networks:
      - trafico-network
    depends_on:
      - mongo
    restart: no