
networks:
  trafico-network:
    driver: bridge

volumes:
  db-data:
  redis-data:


services:

  # Servicio de scraping de Waze
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: waze-scraper
    volumes:
      - ./scraper/src:/app/src
    networks:
      - trafico-network
    restart: unless-stopped
    env_file:
      - mongo.env
    depends_on:
      - mongo
      - redis

  # Servicio de cache con Redis
  redis:
    image: redis:7-alpine
    container_name: waze-cache
    
    ports:
      - "6379:6379"    # Puerto estándar (para tus servicios)
    volumes:
      - redis-data:/data
    networks:
      - trafico-network
    restart: unless-stopped
  # Servicio que administra el cache y políticas

  cache-service:
    build:
      context: ./cache-service
    container_name: waze-cache-service
    env_file: redis.env  # Esto debe estar dentro del servicio, no en la raíz
    networks:
      - trafico-network
    restart: unless-stopped


  traffic-generator:
    build:
      context: ./traffic-generator
    container_name: waze-traffic-gen
    networks:
      - trafico-network
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
  