FROM python:3.9-slim

# 1. Instala dependencias básicas
RUN apt-get update && \
    apt-get install -y \
    openjdk-17-jre-headless \
    wget \
    tar \
    curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 1.1 Configura JAVA_HOME para ARM64
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-arm64
ENV PATH=$PATH:$JAVA_HOME/bin

# 2. Instalar Hadoop
RUN wget https://archive.apache.org/dist/hadoop/common/hadoop-3.2.1/hadoop-3.2.1.tar.gz && \
    tar -xzf hadoop-3.2.1.tar.gz && \
    mv hadoop-3.2.1 /opt/hadoop && \
    rm hadoop-3.2.1.tar.gz

# 2.1 Configurar Hadoop
ENV HADOOP_HOME=/opt/hadoop
ENV PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin
ENV HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop

# 3. Instalar Pig
RUN wget https://downloads.apache.org/pig/pig-0.17.0/pig-0.17.0.tar.gz && \
    tar -xzf pig-0.17.0.tar.gz && \
    mv pig-0.17.0 /opt/pig && \
    rm pig-0.17.0.tar.gz

# 3.1 Configurar entorno Pig
ENV PIG_HOME=/opt/pig
ENV PATH=$PATH:$PIG_HOME/bin    

# 4. Instala solo las dependencias necesarias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copia los archivos de procesamiento
WORKDIR /app
COPY ./src ./src

# 6. Comando de ejecución
CMD ["python", "-u", "src/main.py"]