# Imagen base compatible con ARM64 y x86_64
FROM bde2020/hadoop-base:2.0.0-hadoop2.7.4-java8

# Instalar dependencias necesarias
USER root
RUN apt-get update && \
    apt-get install -y wget unzip curl && \
    rm -rf /var/lib/apt/lists/*

# Instalar Apache Pig manualmente
ENV PIG_VERSION=0.17.0
ENV PIG_HOME=/opt/pig
ENV PATH=$PATH:$PIG_HOME/bin

RUN wget https://downloads.apache.org/pig/pig-${PIG_VERSION}/pig-${PIG_VERSION}.tar.gz && \
    tar -xvzf pig-${PIG_VERSION}.tar.gz -C /opt && \
    mv /opt/pig-${PIG_VERSION} $PIG_HOME && \
    rm pig-${PIG_VERSION}.tar.gz

# Copiar scripts Pig
COPY ./src /scripts

WORKDIR /scripts

CMD ["/bin/bash"]
