version: '3.8'

networks:
  trafico-network:
    driver: bridge

volumes:
  db-data:
  pig_data:

services:
mongo:
    image: mongo:6
    container_name: waze-db
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - trafico-network
    restart: unless-stopped

scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: waze-scraper
    volumes:
      - ./scraper/src:/app/src
      - ./storage:/storage
    networks:
      - trafico-network
    restart: unless-stopped
    env_file:
      - mongo.env
    depends_on:
      - mongo

storage:
    build:
      context: ./storage
    container_name: waze-storage
    volumes:
      - ./storage:/storage
    env_file:
      - mongo.env
    networks:
      - trafico-network
    depends_on:
      - mongo
    restart: no

filter:
    build:
      context: ./filtering
    container_name: filtering
    depends_on:
      - mongo

pig:
    image: suhothayan/hadoop-spark-pig-hive:2.9.2
    container_name: pig
    ports:
      - "50070:50070"
      - "8088:8088"
    volumes:
      - ./pig/scripts:/scripts
      - pig_data:/data