version: '3.8'

networks:
  trafico-network:
    driver: bridge

volumes:
  db-data:

services:



  waze-processing:
    build: ./processing
    container_name: waze-processing
    volumes:
      - ./processing:/app
      - ./hadoop-data:/hadoop-data

    networks:
      - trafico-network

  hadoop:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - CORE_CONF_io_compression_codecs=org.apache.hadoop.io.compress.SnappyCodec
    ports:
      - "50070:50070"
      - "9000:9000"
    volumes:
      - ./hadoop-data/namenode:/hadoop/dfs/name
    networks:
      - trafico-network

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - CORE_CONF_io_compression_codecs=org.apache.hadoop.io.compress.SnappyCodec
    volumes:
      - ./hadoop-data/datanode:/hadoop/dfs/data
    depends_on:
      - hadoop
    networks:
      - trafico-network
