networks:
  trafico-network:
    driver: bridge

volumes:
  db-data:
  processing-results:

services:
  mongo:
    image: mongo:6
    container_name: waze-db
    ports:
      - "27017:27017"
    volumes:
      - ./processing:/app
      - ./hadoop-data:/hadoop-data
      - ./processing/results:/processing

    networks:
      - trafico-network
    restart: unless-stopped

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: waze-scraper
    volumes:
      - ./scraper/src:/app/src
      - ./storage:/storage
    networks:
      - trafico-network
    restart: unless-stopped
    env_file:
      - mongo.env
    depends_on:
      - mongo

  storage:
    build:
      context: ./storage
    container_name: waze-storage
    volumes:
      - ./storage:/storage
    env_file:
      - mongo.env
    networks:
      - trafico-network
    depends_on:
      - mongo
    restart: no

  filter:
    build:
      context: ./filtering
    container_name: filtering
    depends_on:
      - mongo
    networks:
      - trafico-network

  pig:
    build: 
      context: ./processing
    container_name: pig
    ports:
      - "50070:50070"
      - "8088:8088"
    volumes:
      - ./processing/src:/scripts
      - pig_data:/data
      - ./cleaned_data/data_for_pig.json:/data_for_pig.json
    networks:
      - trafico-network
