# cache-service/Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src ./src
COPY mongo.env /app/mongo.env

CMD ["python", "-u", "./src/main.py"]