networks:
  trafico-network:
    driver: bridge

volumes:
  db-data:
  redis-uniform-lru-data:
  redis-uniform-lfu-data:
  redis-exp-lru-data:
  redis-exp-lfu-data:

services:
  mongo:
    image: mongo:6
    container_name: waze-db
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - trafico-network
    restart: unless-stopped

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: waze-scraper
    volumes:
      - ./scraper/src:/app/src
      - ./storage:/storage
    networks:
      - trafico-network
    restart: unless-stopped
    env_file:
      - mongo.env
    depends_on:
      - mongo
      - redis-uniform-lru
      - redis-uniform-lfu
      - redis-exp-lru
      - redis-exp-lfu

  # Redis uniformes (LRU y LFU)
  redis-uniform-lru:
    image: redis:7-alpine
    container_name: redis-uniform-lru
    ports:
      - "6380:6379"
    volumes:
      - redis-uniform-lru-data:/data
    command: redis-server --maxmemory 2mb --maxmemory-policy allkeys-lru
    networks:
      - trafico-network
    restart: unless-stopped

  redis-uniform-lfu:
    image: redis:7-alpine
    container_name: redis-uniform-lfu
    ports:
      - "6381:6379"
    volumes:
      - redis-uniform-lfu-data:/data
    command: redis-server --maxmemory 2mb --maxmemory-policy allkeys-lfu
    networks:
      - trafico-network
    restart: unless-stopped

  # Redis exponencial (LRU y LFU)
  redis-exp-lru:
    image: redis:7-alpine
    container_name: redis-exp-lru
    ports:
      - "6382:6379"
    volumes:
      - redis-exp-lru-data:/data
    command: redis-server --maxmemory 3mb --maxmemory-policy allkeys-lru
    networks:
      - trafico-network
    restart: unless-stopped

  redis-exp-lfu:
    image: redis:7-alpine
    container_name: redis-exp-lfu
    ports:
      - "6383:6379"
    volumes:
      - redis-exp-lfu-data:/data
    command: redis-server --maxmemory 3mb --maxmemory-policy allkeys-lfu
    networks:
      - trafico-network
    restart: unless-stopped

  cache-service:
    build:
      context: ./cache-service
    container_name: waze-cache-service
    env_file: redis.env
    networks:
      - trafico-network
    restart: unless-stopped

  traffic-generator:
    build:
      context: ./traffic-generator
      dockerfile: Dockerfile
    container_name: waze-traffic-gen
    volumes:
      - ./traffic-generator/src:/traffic-generator
      - ./storage:/storage
      - ./cache-service:/cache-service
    networks:
      - trafico-network
    env_file:
      - mongo.env
      - redis.env
    depends_on:
      - mongo
      - redis-uniform-lru
      - redis-uniform-lfu
      - redis-exp-lru
      - redis-exp-lfu
    restart: no

  storage:
    build:
      context: ./storage
    container_name: waze-storage
    volumes:
      - ./storage:/storage
    env_file:
      - mongo.env
    networks:
      - trafico-network
    depends_on:
      - mongo
    restart: no